### 获取新闻分类
GET {{url}}/api/news/categories?page=3&size=3
Accept: */*
Cache-Control: no-cache

### 获取新闻列表
GET {{url}}/api/news/list?categoryId=2&page=2&size=3
Accept: */*
Cache-Control: no-cache

### 创建用户
POST {{url}}/api/users/register
Accept: */*
Cache-Control: no-cache
Content-Type:  application/json

{
  "username": "七月的极光",
  "nickname": "太阳之子",
  "password": "112"
}