### 获取新闻分类
GET {{url}}/api/news/categories?page=3&size=3
Accept: */*
Cache-Control: no-cache

### 获取新闻列表
GET {{url}}/api/news/list?categoryId=2&page=2&size=3
Accept: */*
Cache-Control: no-cache

### 创建用户
POST {{url}}/api/users/register
Accept: */*
Cache-Control: no-cache
Content-Type:  application/json

{
  "username": "七月的极光",
  "nickname": "太阳之子",
  "password": "112"
}

### 根据token获取用户信息
GET {{url}}/api/users/get_user_by_token
Accept: */*
Cache-Control: no-cache
Authorization: Bearer 48cdf85a-c663-4f62-95c2-37fd6b653f1f

### 根据token获取用户信息-2
GET {{url}}/api/users/get_user_by_token_2
Accept: */*
Cache-Control: no-cache
Authorization: Bearer ddedafd4-41b6-4833-a224-34c40b80c08a

### 更新用户信息
POST {{url}}/api/users/update_user_info
Accept: */*
Cache-Control: no-cache
Content-Type:  application/json
Authorization: Bearer ddedafd4-41b6-4833-a224-34c40b80c08a

{
  "avatar": "http://def",
  "nickname": "太阳之子_3"
}